# Generated by Django 4.2.6 on 2023-10-30 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("money", models.FloatField(default=0)),
                ("bonus", models.FloatField(default=0)),
                (
                    "expire",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            11,
                            6,
                            13,
                            56,
                            32,
                            251035,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
        ),
    ]
