# Generated by Django 4.2.6 on 2023-10-30 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Prices", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="expire",
        ),
        migrations.AddField(
            model_name="price",
            name="expireDate",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(
                    2023, 11, 6, 14, 40, 30, 554637, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
