# Generated by Django 4.2.6 on 2023-10-30 18:38

import Prices.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Prices", "0004_price_expiredate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="expireDate",
            field=models.DateField(
                blank=True,
                default=Prices.models.default_expire_date,
                editable=False,
                null=True,
            ),
        ),
    ]
