# Generated by Django 4.2.6 on 2023-10-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Prices", "0005_alter_price_expiredate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="expireDate",
            field=models.DateField(
                blank=True, default="2023-11-06T18:41:59", editable=False, null=True
            ),
        ),
    ]
