# Generated by Django 4.2.6 on 2023-10-30 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Prices", "0006_alter_price_expiredate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="creationDate",
        ),
        migrations.RemoveField(
            model_name="price",
            name="expireDate",
        ),
    ]
