# Generated by Django 4.1.5 on 2023-08-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("price", models.FloatField()),
                ("isFree", models.BooleanField(default=False)),
                ("isPremium", models.BooleanField(default=False)),
                ("minimumPlayableAge", models.IntegerField(blank=True, null=True)),
                ("company", models.CharField(max_length=60)),
                ("description", models.TextField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("downloads", models.FloatField(blank=True, null=True)),
                ("memory", models.FloatField()),
            ],
        ),
    ]
