# Generated by Django 4.1.5 on 2023-08-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Gamesapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.FloatField()),
                ("expireDate", models.DateField()),
                (
                    "gameId",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="Gamesapp.game"
                    ),
                ),
            ],
        ),
    ]
