# Generated by Django 4.1.5 on 2023-08-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Gamesapp", "0002_game_image_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="introductionVideo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
