# Generated by Django 4.1.5 on 2023-08-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Gamesapp", "0004_gamesale_tag_rename_minimumplayableage_game_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="Gamesapp.tag"),
        ),
        migrations.DeleteModel(
            name="Discount",
        ),
    ]
