# Generated by Django 4.1.5 on 2023-09-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Gamesapp", "0005_alter_game_tags_delete_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="multiplayer",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
