# Generated by Django 4.1.5 on 2023-08-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Usersapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="numberOfGaims",
            new_name="numberOfGames",
        ),
    ]
