# Generated by Django 4.1.5 on 2023-08-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usersapp", "0003_profile_ispremium"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
