# Generated by Django 4.1.5 on 2023-09-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Usersapp", "0004_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="username",
        ),
    ]
