# Generated by Django 4.2.6 on 2023-10-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Usersapp", "0006_profile_coins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="coins",
            field=models.FloatField(default=0),
        ),
    ]
