# Generated by Django 4.2.6 on 2023-10-29 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Usersapp", "0007_alter_profile_coins"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="coins",
        ),
    ]
