# Generated by Django 4.2.6 on 2023-10-30 13:56

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Usersapp", "0009_alter_profile_accountmoney"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilePayments",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("Usersapp.profile",),
        ),
    ]
