# Generated by Django 4.1.5 on 2023-08-12 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Gamesapp", "0002_game_image_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileGameRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gameId",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="Gamesapp.game"
                    ),
                ),
                (
                    "userId",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("createDate", models.DateTimeField(auto_now_add=True)),
                ("updateDate", models.DateTimeField(auto_now=True)),
                (
                    "idGame",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="Gamesapp.game"
                    ),
                ),
                (
                    "idUser",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
